version: "3"
services:
  custom-api:
    build: .
    ports:
      - "5000:5000"
    # env_file:
    #   - .env
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    restart: unless-stopped
